#pragma once

#define ARENA_WIDTH 200
#define ARENA_HEIGHT 200
#define ARENA_DEPTH 200
#define ASTEROID_COUNT 50

#define SCORE_PER_SECOND 1
#define SCORE_PER_ASTEROID_SHOT 20
#define SCORE_PER_PLAYER_SHOT 100

#define LIFES 3
#define INVULNERABLE_AFTER_HIT 1
#define INVULNERABLE_ON_START 5
#define SHOOT_COOLDOWN 0.5

#define ASTEROID_RADIUS 1
#define SPACECRAFT_RADIUS 2
#define PROJECTILE_RADIUS 0.2
#define SPACECRAFT_MAX_SPEED 2
#define ASTEROID_MAX_SPEED 1
#define BULLET_SPPED 3

#define IGNORE_Z_AXIS true
