#pragma once

#define SERVER_PORT 2000
#define BUFFER_SIZE 10000

#define FIXED_TIME_DELTA 0.1

#define ARENA_WIDTH 200
#define ARENA_HEIGHT 200
#define ARENA_DEPTH 200
#define ASTEROID_COUNT 20

#define SCORE_PER_SECOND 1
#define SCORE_PER_ASTEROID_SHOT 20
#define SCORE_PER_PLAYER_SHOT 100

#define LIFES 3
#define INVULNERABLE_AFTER_HIT 1
#define INVULNERABLE_ON_START 5
#define SHOOT_COOLDOWN 0.5

#define ASTEROID_RADIUS 1
#define SPACECRAFT_RADIUS 2
#define BULLET_RADIUS 0.2
#define SPACECRAFT_SPEED 20
#define ASTEROID_SPEED 10
#define BULLET_SPEED 30

#define IGNORE_Z_AXIS true
